### ISSUE TITLE
Hi, Errrneist

### ISSUE THREAD

**Issue by tthrx** [Errrneist/Hackintosh-Thinkpad-P50#1]
Could you point out which parts are functioning well and which are not.
Basically there are WIFI&BT, USB3,  intel p530 and Nvidia Graphics, Express card reader, Thunderbolt, HDMI, Battery management, Trackpad, Rad Track dot, etc.
My P50 is almost the same as yours,  I tried to install Seirra following posts in "tonymacx86" lots of times months ago, but I was not that lucky and got tired at that time.
Thank you for sharing.

**Comment by tthrx** [comment]
突然发现你也是中国人，哈哈
麻烦告知一下那些好用，那些不好用啊，我都没装成过。。。
后来没时间就没再折腾了
能否指点一下
我的CPU : E3-1535Mv5, 32G Ram, intel HD P530 & Nvidia Quadro M2000M 非高分屏，其他应该都差不多

**Comment by wu-hongjun** [comment]
那我们基本一样……你的看起来还好装一点
有一阵子一直装不上，但是后来我发现缺了emuvariable.efi（好像是这么拼的）
不然装不上……P50卖了换了台Aero15 但是我觉得我这个版本应该是蛮完整的了！
加油啦

**Comment by tthrx** [comment]
好的，谢谢
